
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: daydev (https://sketchfab.com/daydev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-gate-inn-with-neon-6245309e652144bdb91b2d6188b18b11
Title: Dragon Gate Inn with Neon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HackerRoom = (props) => {
  const { nodes, materials } = useGLTF('/models/dragon_gate_inn_with_neon.glb')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.099}>
        <group position={[0, 0, 0.106]} scale={6.549}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_0.geometry}
            material={materials.Rock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Dirt}
          />
        </group>
        <group position={[-1.128, -3.534, 1.305]} scale={1.197}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_0.geometry}
            material={materials.Tube}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_1.geometry}
            material={materials.WallRed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={materials.Roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4.geometry}
            material={materials.ChineseWindows}
          />
        </group>
        <group position={[-1.317, -3.009, 4.493]} scale={1.297}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_0.geometry}
            material={materials.Roof}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials.Wood_red}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube005_2.geometry}
            material={materials.Gold}
          />
        </group>
        <group position={[-0.35, -1.083, 1.081]} scale={0.327}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_0.geometry}
            material={materials.LionDoors}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.Rock}
          />
        </group>
        <group position={[-4.471, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[0.353, -5.482, 0]} scale={0.787}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree001_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves001_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[3.959, 0.1, 1.762]} scale={1.868}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_0.geometry}
            material={materials.Rock}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials.GreenDark}
          />
        </group>
        <group position={[3.561, 0.034, 1.708]} scale={0.596}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder028_0.geometry}
            material={materials.WallRed}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder028_1.geometry}
            material={materials.GreenDark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder028_2.geometry}
            material={materials.Gold}
          />
        </group>
        <group position={[3.413, -4.085, 0]} scale={0.396}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree002_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves002_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[3.565, 2.83, 0]} scale={0.664}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree003_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves003_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[2.885, 3.893, 0]} rotation={[0, 0, 0.459]} scale={0.767}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree004_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves004_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[2.604, -4.905, 0]} rotation={[0, 0, -0.806]} scale={0.396}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree005_0.geometry}
            material={materials.Tree}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves005_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[3.563, 0.093, 5.093]} scale={0.678}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder037_0.geometry}
            material={materials.Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder037_1.geometry}
            material={materials.Rock}
          />
        </group>
        <group position={[0.354, 3.533, 0]} scale={0.629}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree006_0.geometry}
            material={materials.Bamboo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves006_0.geometry}
            material={materials.Leave}
          />
        </group>
        <group position={[-2.442, 2.767, 2.739]} scale={0.391}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.tree007_0.geometry}
            material={materials.Bamboo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.leaves007_0.geometry}
            material={materials.Leave}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_0.geometry}
          material={materials.GreenDark}
          position={[-0.37, -3.733, 3.266]}
          scale={0.259}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_0.geometry}
          material={materials.Gold}
          position={[-0.556, -2.778, 3.686]}
          scale={0.075}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_0.geometry}
          material={materials.ChineseWindows}
          position={[0.28, -3.05, 1.691]}
          scale={0.327}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_0.geometry}
          material={materials.ChineseWindows}
          position={[0.28, -3.936, 1.691]}
          scale={0.327}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_0.geometry}
          material={materials.Tree}
          position={[0.28, -4.718, 1.764]}
          scale={0.327}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_0.geometry}
          material={materials.GreenDark}
          position={[-0.453, -2.407, 5.028]}
          rotation={[0, 0, 1.56]}
          scale={0.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_0.geometry}
          material={materials.GreenDark}
          position={[-3.155, -2.407, 5.028]}
          rotation={[0, 0, 1.56]}
          scale={0.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_0.geometry}
          material={materials.Tube}
          position={[0.185, -2.778, 2.498]}
          rotation={[0, 0, -1.503]}
          scale={0.034}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_0.geometry}
          material={materials.Tube}
          position={[-0.447, -0.526, 2.519]}
          rotation={[0, 0, -1.503]}
          scale={0.034}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_0.geometry}
          material={materials.Tube}
          position={[-0.429, -4.904, 2.533]}
          rotation={[0, 0, -3.047]}
          scale={0.052}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_0.geometry}
          material={materials.Tube}
          position={[-1.009, -0.841, 4.917]}
          rotation={[0, 0, -1.503]}
          scale={0.072}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_0.geometry}
          material={materials.Gold}
          position={[-3.293, -4.276, 0.888]}
          rotation={[0, 0, 1.863]}
          scale={0.096}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_0.geometry}
          material={materials.GreenDark}
          position={[-1.945, -3.436, 6.264]}
          scale={0.269}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_0.geometry}
          material={materials.GreenDark}
          position={[-1.945, -1.424, 6.264]}
          rotation={[-0.012, 0.032, 3.138]}
          scale={0.269}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_0.geometry}
          material={materials.Bowl}
          position={[-1.825, -5.085, 0.568]}
          scale={0.386}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_0.geometry}
          material={materials.Bowl}
          position={[-0.944, -5.117, 0.568]}
          scale={0.429}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_0.geometry}
          material={materials.Woods}
          position={[-1.071, -5.186, 1.456]}
          scale={0.258}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_0.geometry}
          material={materials.Woods}
          position={[-2.585, -5.186, 0.505]}
          rotation={[0, -0.997, 0]}
          scale={0.258}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_0.geometry}
          material={materials.LionDoors}
          position={[-0.35, -1.833, 1.081]}
          scale={0.327}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_0.geometry}
          material={materials.Neon}
          position={[0.009, -0.595, 0.568]}
          rotation={[0, 0, -1.479]}
          scale={0.234}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_0.geometry}
          material={materials.Gold}
          position={[0.347, -2.503, 2.403]}
          scale={0.091}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_0.geometry}
          material={materials.Gold}
          position={[0.338, -4.847, 2.403]}
          scale={0.091}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018_0.geometry}
          material={materials.Tree}
          position={[0.113, -2.502, 0.923]}
          rotation={[0, 1.513, 0]}
          scale={0.054}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_0.geometry}
          material={materials.Tree}
          position={[0.113, -2.502, 0.674]}
          rotation={[0, 0.861, 0]}
          scale={0.043}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_0.geometry}
          material={materials.Tree}
          position={[0.113, -2.502, 2.005]}
          rotation={[-3.101, 1.144, 3.136]}
          scale={0.043}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_0.geometry}
          material={materials.Neon}
          position={[0.419, -2.501, 1.559]}
          scale={0.171}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_0.geometry}
          material={materials.Windows}
          position={[-1.098, -2.099, 4.225]}
          scale={0.327}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021_0.geometry}
          material={materials.GreenDark}
          position={[-2.045, -5.06, 5.028]}
          rotation={[0.12, 1.443, -0.139]}
          scale={0.054}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_0.geometry}
          material={materials.GreenDark}
          position={[-2.045, 0.145, 5.028]}
          rotation={[0.12, 1.443, -0.139]}
          scale={0.054}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder024_0.geometry}
          material={materials.Bowl}
          position={[-0.593, -5.009, 5.078]}
          rotation={[-0.93, -0.538, 0.801]}
          scale={0.082}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder023_0.geometry}
          material={materials.Bowl}
          position={[-3.1, -5.136, 5.047]}
          rotation={[-0.926, 0.391, 0.187]}
          scale={0.082}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025_0.geometry}
          material={materials.Bowl}
          position={[-0.495, 0.153, 5.047]}
          rotation={[0.868, -0.584, -3.003]}
          scale={0.082}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_0.geometry}
          material={materials.Bowl}
          position={[-3.056, 0.185, 4.985]}
          rotation={[0.872, 0.348, -2.25]}
          scale={0.082}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_0.geometry}
          material={materials.Gold}
          position={[-0.448, -0.303, 3.4]}
          rotation={[0, 0, -1.588]}
          scale={0.042}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_0.geometry}
          material={materials.Mist}
          position={[0.614, -0.322, 3.913]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029_0.geometry}
          material={materials.Bamboo}
          position={[3.503, -1.86, 0.233]}
          scale={0.103}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder030_0.geometry}
          material={materials.Bamboo}
          position={[3.489, -0.38, 1.817]}
          scale={0.073}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus001_0.geometry}
          material={materials.LionDoors}
          position={[1.96, -1.86, 1.798]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus000_0.geometry}
          material={materials.LionDoors}
          position={[1.96, -1.86, 3.509]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus002_0.geometry}
          material={materials.LionDoors}
          position={[1.96, -1.86, 5.143]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus003_0.geometry}
          material={materials.LionDoors}
          position={[1.933, 2.114, 5.143]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus004_0.geometry}
          material={materials.LionDoors}
          position={[1.933, 2.114, 3.509]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus005_0.geometry}
          material={materials.LionDoors}
          position={[1.933, 2.114, 1.798]}
          rotation={[0.881, 0, 0]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder031_0.geometry}
          material={materials.Woods}
          position={[3.904, -2.019, 1.13]}
          scale={0.188}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder032_0.geometry}
          material={materials.Bowl}
          position={[3.997, -1.969, 0.484]}
          scale={0.312}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033_0.geometry}
          material={materials.Bowl}
          position={[4.5, -2.264, 0.484]}
          scale={0.312}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder034_0.geometry}
          material={materials.Woods}
          position={[4.527, -2.291, 1.119]}
          scale={0.188}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_0.geometry}
          material={materials.ChineseWindows}
          position={[2.124, -2.738, 1.926]}
          rotation={[-0.246, 0, 0]}
          scale={0.022}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder036_0.geometry}
          material={materials.ChineseWindows}
          position={[4.416, -2.556, 1.926]}
          rotation={[-0.187, 0.161, -0.701]}
          scale={0.022}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_0.geometry}
          material={materials.Summer}
          position={[3.132, -1.792, 3.155]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_0.geometry}
          material={materials.Neon}
          position={[-0.126, 2.208, 4.345]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_0.geometry}
          material={materials.Memori}
          position={[0.739, -1.997, 3.329]}
          scale={0.596}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_0.geometry}
          material={materials.Memori}
          position={[0.667, -1.997, 6.105]}
          scale={0.596}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_0.geometry}
          material={materials.Tree}
          position={[1.661, -2.155, 6.61]}
          rotation={[-1.455, 0.988, -3.103]}
          scale={0.043}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_0.geometry}
          material={materials.Neon}
          position={[5.152, 4.1, 4.345]}
          rotation={[0, 0, -1.603]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_0.geometry}
          material={materials.Rock}
          position={[2.07, -3.238, 0.288]}
          scale={0.438}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001_0.geometry}
          material={materials.Rock}
          position={[4.068, -3.053, 0.288]}
          scale={0.225}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002_0.geometry}
          material={materials.Rock}
          position={[4.068, 2.625, 0.288]}
          scale={0.415}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003_0.geometry}
          material={materials.Rock}
          position={[3.31, 3.452, 0.256]}
          scale={0.415}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038_0.geometry}
          material={materials.Mountain}
          position={[-1.222, 3.162, 2.488]}
          scale={2.421}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_0.geometry}
          material={materials.Rock}
          position={[-3.539, 1.305, 0.497]}
          scale={0.642}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_0.geometry}
          material={materials.Memori}
          position={[-1.257, -5.094, 3.985]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_0.geometry}
          material={materials.Spark}
          position={[0.283, -3.765, 3.163]}
          scale={0.389}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/dragon_gate_inn_with_neon.glb')

export default HackerRoom
